server:
  port: 8081

spring:
  application:
    name: online-user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*/*.xml
  type-aliases-package: com.java.provider.dao.entitys.*